config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root 'lessons#index'
  devise_for :users
  resources :users
  resources :lessons do 
    resources :comments
  end
  resources :topics
  resources :comments
  resources :favorites
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :lesson
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user, dependent: :destroy
	has_many :join_favorite_lessons, dependent: :destroy
  	has_many :lessons, through: :join_favorite_lessons, dependent: :destroy
end

app/models/join_favorite_lesson.rb
class JoinFavoriteLesson < ApplicationRecord
	belongs_to :lesson, dependent: :destroy
  	belongs_to :favorite, dependent: :destroy

  	validates_uniqueness_of :lesson, scope: :favorite_id
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :topic, optional: true
  has_many :comments, dependent: :destroy
  has_many :join_favorite_lessons, dependent: :destroy
  has_many :favorites, through: :join_favorite_lessons, dependent: :destroy
  has_many :rates
  has_many :proposals

  validates :title, length: { minimum: 5 }
  validates :content, length: { minimum: 50 }
end

app/models/proposal.rb
class Proposal < ApplicationRecord
	belongs_to :user
	belongs_to :lesson
end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :user
	belongs_to :lesson
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :lessons, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  after_create :attribute_favorite

  has_many :lessons, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :favorite, dependent: :destroy
  has_many :rates
  has_many :proposals

  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def attribute_favorite
    Favorite.create(user: self)
  end

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
 def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    if params[:title]
      @lessons = Lesson.where('title ILIKE ?', "%#{params[:title]}%")
    else
      @lessons = Lesson.last(10).reverse
    end
  end

  def show
  	@lesson = Lesson.find(params[:id])
    $less = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  	@topics = Topic.all
  end


  def create
    @user = current_user
    @topics = Topic.all
    @lesson = Lesson.new(user: @user, title: params[:title], content: params[:content], topic_id: params[:top])

    if @lesson.save
      redirect_to users_index_path
    else
      render 'lessons/new'
    end
  end

  def lesson_params
    params.require(:lesson).permit(:title)
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to users_index_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def show
  	@topic_attribute = Topic.find(params[:id])
  	@topic = Lesson.where(topic_id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	def show

		@user = User.find(params[:id])

	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		user_params = params.require(:user).permit(:first_name, :last_name, :city, :school, :diploma)
		if @user.update(user_params)
			flash[:success] = "Ton profil est modifié"
			redirect_to user_path(:id => current_user.id)
		else
			render :edit
		end
	end

	def index
		@user = current_user
		@all_my_lessons = @user.lessons
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearnIt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper/css/swiper.min.css">

    <script src="https://unpkg.com/swiper/js/swiper.js"></script>
    <script src="https://unpkg.com/swiper/js/swiper.min.js"></script>

    <link rel="stylesheet" href="path/to/swiper.min.css">
    <script src="//cdn.ckeditor.com/4.13.1/standard/ckeditor.js"></script>

  </head>

  <body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">
    <div class="site-wrap">
      <div class="site-mobile-menu site-navbar-target">
        <div class="site-mobile-menu-header">
          <div class="site-mobile-menu-close mt-3">
            <span class="icon-close2 js-menu-toggle"></span>
          </div>
        </div>
      <div class="site-mobile-menu-body"></div>
    </div>

    <header class="site-navbar py-4 js-sticky-header site-navbar-target" role="banner" style="margin-top: 12px;">
      <%= render "shared/navbar" %>
    </header>


    <div class="site-section bg-image overlay" style="background-color: #636871;">
    </div>

    <%= yield %>
    <footer class="footer-section bg-white">
      <%= render "shared/footer" %>
    </footer>

    <script src="path/to/swiper.min.js"></script>

    <!-- Initialize Swiper -->
    <script>
    var swiper = new Swiper('.swiper-container', {
      spaceBetween: 30,
      centeredSlides: true,
      autoplay: {
        delay: 3500,
        disableOnInteraction: false,
      },
      pagination: {
        el: '.swiper-pagination',
        clickable: true,
      },
      navigation: {
        nextEl: '.swiper-button-next',
        prevEl: '.swiper-button-prev',
      },
    });
    </script>

    <script>
      CKEDITOR.replace( 'content' );
    </script>

  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/navbar.html.erb
<!DOCTYPE htmL>

<html>

    <head>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
    <link href="/your-path-to-fontawesome/css/brands.css" rel="stylesheet">
    <link href="/your-path-to-fontawesome/css/solid.css" rel="stylesheet">

    <link href="../stylesheets/application.css" rel="stylesheet">
  

    </head>

    <body>

           <!-- Navbar -->

           <header>

                    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #faaa62;">
                    <a class="navbar-brand" href="#">Learnit</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button> 
                    
                    
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">            
                                <li class="nav-item">
                                    
                                        <a class="nav-link dropdown-toggle" href="#" id="Matieres" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Matières
                                        </a>
                                        
                                        <div class="dropdown-menu" aria-labelledby="Matieres">
                                            
                                            <a class="dropdown-item" href="#">Mathématiques</a>
                                            <a class="dropdown-item" href="#">Français</a>
                                            <a class="dropdown-item" href="#">Histoire-Géo</a>
                                            <a class="dropdown-item" href="#">Anglais</a>
                                            <a class="dropdown-item" href="#">EPS</a>
                                            <a class="dropdown-item" href="#">SVT</a>
                                            <a class="dropdown-item" href="#">Physique-Chimie</a>

                                            <a class="dropdown-item" href="#">Something else here</a>

                                        </div>

                                    </li>    
                                        
                                    <li class="nav-item">     
                                    
                                    <a class="nav-link dropdown-toggle" href="#" id="Cours" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Mes cours
                                    </a>
                                    
                                    <div class="dropdown-menu" aria-labelledby="Cours">
                                        
                                        <a class="dropdown-item" href="#">Ajouter un cours</a>
                                        <a class="dropdown-item" href="#">Mes favoris</a>
                                    
                                        
                                    </div>

                                  
                                    
                                </li>

                           </ul>
                    <div class="navbarRigth">
                           <form class="form-inline my-2 my-lg-0">
                           <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                           <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                            </form>

                     
                           
                    </div>
                    
   
                </div>

                
            </nav>

           
        </header>


 <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>

</html>

app/views/shared/_footer.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-4">
      <h3>A propos de Learn it</h3>
      <p>Learn it permet de partager tes meilleures fiches de cours avec le reste du monde :)</p>
    </div>

    <div class="col-md-3 ml-auto">
      <h3>Liens utiles</h3>
      <ul class="list-unstyled footer-links">
        <li><a href="/">Accueil</a></li>
        <% if current_user %>
          <li><a href="/lessons/new">Ajouter un cours</a></li>
        <% else %>
          <li><%= link_to "Ajouter un cours", new_user_session_path %></li>
        <% end %>
      </ul>
    </div>

    <div class="col-md-4">
      <h3>Aide LearnIt</h3>
      <p>Tu peux aider Learn It en faisant un don :
       <%= link_to "Faire un don", new_charge_path %>
         </p>
    </div>
  </div>
    <div class="row pt-5 mt-5 text-center">
      <div class="col-md-12">
        <div class="border-top pt-5">
          <p>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
          Copyright &copy 2019 All rights reserved | This template is made with <i class="icon-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank" >Colorlib</a>
          <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
        </p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar">
  <div class="site-logo ml-4 mr-2"><a href="/">Learn it</a></div>
  <div class="text-center ml-4">
    <nav class="site-navigation position-relative text-right" role="navigation">
      <ul class="site-menu main-menu js-clone-nav mx-auto d-none d-lg-block  m-0 p-0">
        <li><a href="#" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Matières </a>
          <ul class="dropdown-menu">
            <% if current_user %>
              <% Topic.all.each do |topic| %>
              <li><%= link_to topic.name, topic_path(topic.id) %></li>
              <% end %>
            <% else %>
              <% Topic.all.each do |topic| %>
              <li><%= link_to topic.name, new_user_session_path %></li>
              <% end %>
            <% end %>
          </ul>
        </li>
        <li><a href="#" class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Mes cours </a>
          <ul class="dropdown-menu">
            <% if current_user %>
                <li><%= link_to "Ajouter un cours", new_lesson_path %></li>
                <li><%= link_to "Mes cours partagés", users_index_path %></li>
                <li><%= link_to "Mes cours favoris", favorite_path(current_user.id) %></li>
            <% else %>
                <li><%= link_to "Ajouter un cours", new_user_session_path %></li>
                <li><%= link_to "Mes cours partagés", new_user_session_path %></li>
                <li><%= link_to "Mes cours favoris", new_user_session_path %></li>
            <% end %>
          </ul>
        </li>
      </ul>
    </nav>
  </div>
    <%= form_tag(lessons_path, method: :get) do %>
      <%= text_field_tag :title, params[:title], placeholder: 'Rechercher un cours', class: 'text-fiels' %>
      <%= submit_tag 'Search', name: nil, redirect_to: lessons_path, class: 'btn-search' %>
    <% end %>
  <div class="ml-auto w-25">
    <nav class="site-navigation position-relative text-right" role="navigation">
      <ul class="site-menu main-menu site-menu-dark js-clone-nav mr-auto d-none d-lg-block m-0 p-0">
      <form>
      <% if current_user %>
        <button class="btn btn-link" type="submit"><%= link_to "Mon profil", users_show_path(:id => current_user.id) %></button>
        <button class="btn btn-link" type="submit"><%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %></button>
        <% else %>
        <button class="btn btn-link" type="submit"><%= link_to "Se connecter", new_user_session_path%></button>
        <button class="btn btn-link" type="submit"><%= link_to "S'inscrire", new_user_registration_path%></button>
      <% end %>
      </form>
      </ul>
    </nav>
    <a href="#" class="d-inline-block d-lg-none site-menu-toggle js-menu-toggle text-black float-right"><span class="icon-menu h3"></span></a>
  </div>
</div>