config/routes.rb
Rails.application.routes.draw do
  get 'users/index'
  get 'users/show'
  root 'lessons#index'
  devise_for :users
  resources :users
  resources :lessons do 
    resources :comments
  end
  resources :topics
  resources :comments
  resources :favorites
  resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
	belongs_to :user
	belongs_to :lesson
end

app/models/favorite.rb
class Favorite < ApplicationRecord
	belongs_to :user, dependent: :destroy
	has_many :join_favorite_lessons, dependent: :destroy
  	has_many :lessons, through: :join_favorite_lessons, dependent: :destroy
end

app/models/join_favorite_lesson.rb
class JoinFavoriteLesson < ApplicationRecord
	belongs_to :lesson, dependent: :destroy
  	belongs_to :favorite, dependent: :destroy

  	validates_uniqueness_of :lesson, scope: :favorite_id
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  belongs_to :user
  belongs_to :topic, optional: true
  has_many :comments, dependent: :destroy
  has_many :join_favorite_lessons, dependent: :destroy
  has_many :favorites, through: :join_favorite_lessons, dependent: :destroy
  has_many :rates
  has_many :proposals

  validates :title, length: { minimum: 5 }
  validates :content, length: { minimum: 50 }
end

app/models/proposal.rb
class Proposal < ApplicationRecord
	belongs_to :user
	belongs_to :lesson
end

app/models/rate.rb
class Rate < ApplicationRecord
	belongs_to :user
	belongs_to :lesson
end

app/models/topic.rb
class Topic < ApplicationRecord
  has_many :lessons, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  after_create :welcome_send
  after_create :attribute_favorite

  has_many :lessons, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_one :favorite, dependent: :destroy
  has_many :rates
  has_many :proposals

  
  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end

  def attribute_favorite
    Favorite.create(user: self)
  end

  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
 def new
end

def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create({
    email: params[:stripeEmail],
    source: params[:stripeToken],
  })

  charge = Stripe::Charge.create({
    customer: customer.id,
    amount: @amount,
    description: 'Rails Stripe customer',
    currency: 'usd',
  })

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def create
    @lesson = Lesson.find(params[:lesson_id])
    @create_comment = Comment.new(title: params[:title], content: params[:content], lesson: $less, user: current_user)
    if @create_comment.save
      flash[:success] = "Votre commentaire a bien été ajouté"
      redirect_to lesson_path(@lesson.id)
    else
      flash[:error] = "Erreur lors de l'ajour du commentaire. Veuillez réessayer"
      redirect_to lesson_path(@lesson.id)
    end
  end

  def destroy
      @lesson = Lesson.find(params[:lesson_id])
      @comment = Comment.find(params[:id])
      @comment.destroy
      redirect_to lesson_path(@lesson.id)
    end


 

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def show
  	 @fav = Favorite.find_by(user_id: current_user.id)
  end

  def update
    if current_user
       Favorite.find_by(user_id: current_user.id).lessons << $less
    else
       redirect_to new_user_session_path
    end
  end

  def destroy
    JoinFavoriteLesson.delete(lesson_to_delete)
    redirect_to favorite_path(current_user.id)
  end

  def lesson_to_delete
    fav = Favorite.find_by(user_id: current_user.id)
    return JoinFavoriteLesson.find_by(favorite_id: fav.id, lesson_id: params[:id])
  end


end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  def index
    if params[:title]
      @lessons = Lesson.where('title ILIKE ?', "%#{params[:title]}%")
    else
      @lessons = Lesson.last(10).reverse
    end
  end

  def show
  	@lesson = Lesson.find(params[:id])
    $less = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  	@topics = Topic.all
  end


  def create
    @user = current_user
    @topics = Topic.all
    @lesson = Lesson.new(user: @user, title: params[:title], content: params[:content], topic_id: params[:top])

    if @lesson.save
      redirect_to users_index_path
    else
      render 'lessons/new'
    end
  end

  def lesson_params
    params.require(:lesson).permit(:title)
  end

  def destroy
    @lesson = Lesson.find(params[:id])
    @lesson.destroy
    redirect_to users_index_path
  end

end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController

  def show
  	@topic_attribute = Topic.find(params[:id])
  	@topic = Lesson.where(topic_id: params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  	def show

		@user = User.find(params[:id])

	end
	
	def edit
		@user = User.find(params[:id])
	end
	
	def update
		@user = User.find(params[:id])
		user_params = params.require(:user).permit(:first_name, :last_name, :city, :school, :diploma)
		if @user.update(user_params)
			flash[:success] = "Ton profil est modifié"
			redirect_to user_path(:id => current_user.id)
		else
			render :edit
		end
	end

	def index
		@user = current_user
		@all_my_lessons = @user.lessons
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/topics_helper.rb
module TopicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/favorites/show.html.erb
<h2 class="text-black title mb-4"> Mes cours favoris </h2>
<div class="center mt-4" >
    <div class="card">
      <div class="row banniere">
        <% @fav.lessons.reverse.each do |x| %>
          <div class="element">
            <div class="card-body">
              <div class="text-card">
                <h5 class="card-title"><%= x.title %></h5>
                <h6 class="card-subtitle mb-2 text-muted"><%= x.topic.name %></h6>
                <h6 class="card-subtitle mb-2 text-muted"> <%= "Leçon de : " %><%= x.user.first_name %> <%= x.user.last_name %></h6>
                <p class="card-text"><%= strip_tags(x.content[0..70]) %></p>
              </div>
              <div class="btn-card">
                <div class="btn-group">
                  <%= link_to "Consulter ce cours", lesson_path(x.id), class: "btn btn-primary btn-index" %>
                  <%= link_to 'Supprimer des favoris', favorite_path(x.id), method: :delete, data: { confirm: 'Supprimer des favoris ?' }, class: "btn btn-primary btn-index ml-1" %> 
                </div>
              </div>
            </div>
            <div class="separator"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/lessons/index.html.erb
<% if params[:title] %>
  <div class="center mt-4" >
    <div class="card">
      <div class="row banniere">
        <div class="">

          <% @lessons.each do |lesson| %>
            <div class="element">
              <div class="card-body">
                <div class="text-card">
                  <h4 class="card-title"><%= lesson.title %></h4>
                  <h6 class="card-subtitle mb-2 text-muted"><%= lesson.topic.name %></h6>
                  <h6 class="card-subtitle mb-2 text-muted"> <%= "Leçon de : " %><%= lesson.user.first_name %> <%= lesson.user.last_name %></h6>
                  <p class="card-text"><%= strip_tags(lesson.content[0..90]) %></p>
                </div>
                <div class="btn-card">
                  <div class="btn-group">
                  <% if current_user %>
                      <%= link_to "Consulter", lesson_path(lesson.id), class: "btn btn-primary btn-index"  %>
                  <% else %>
                      <%= link_to "Connecte-toi pour consulter", new_user_session_path, class: "btn btn-primary btn-index"  %>
                  <% end %>
                  </div>
                </div>
              </div>
              <div class="separator"></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% else %>
  <!-- Swiper -->
  <div class="swiper-container">
    <div class="swiper-wrapper swiper-heigth">
      <div class="swiper-slide">
        <%= image_tag('banner.jpg', class: 'banner') %>
      </div>
      <div class="swiper-slide">
        <%= image_tag('banner4.jpg', class: 'banner') %>
      </div>
      <div class="swiper-slide">
        <%= image_tag('banner2.jpg', class: 'banner') %>
      </div>
      <div class="swiper-slide">
        <%= image_tag('banner3.jpg', class: 'banner') %>
      </div>
    </div>
  </div>

  <h2 class="text-black title mb-4">
    Learn it te permet :
  </h2>

  <div class="cards-icon">
    <div class="card-icon">
      <%= image_tag('world.svg', class: "width_50") %>
      <p>
        <br>
        De consulter des cours partout dans le monde
      </p>
    </div>
    <div class="grey-border"></div>
    <div class="card-icon">
      <%= image_tag('laptop.svg', class: "width_50") %>
      <p>
        <br>
        De partager tes meilleures ressources
      </p>
    </div>
    <div class="grey-border"></div>
    <div class="card-icon">
      <%= image_tag('thought.svg', class: "width_50") %>
      <p>
        <br>
        De participer au développement du savoir
      </p>
    </div>
  </div>
  <h2 class="text-black title mb-4">
    Les 10 derniers cours partagés par les membres de Learn it :
  </h2><br/>

  <div class="center mt-4" >
    <div class="card">
      <div class="row banniere">
        <div class="">

          <% @lessons.each do |lesson| %>
            <div class="element">
              <div class="card-body">
                <div class="text-card">
                  <h4 class="card-title"><%= lesson.title %></h4>
                  <h6 class="card-subtitle mb-2 text-muted"><%= lesson.topic.name %></h6>
                  <h6 class="card-subtitle mb-2 text-muted"> <%= "Leçon de : " %><%= lesson.user.first_name %> <%= lesson.user.last_name %></h6>
                  <p class="card-text"><%= strip_tags(lesson.content[0..90]) %></p>
                </div>
                <div class="btn-card">
                  <div class="btn-group">
                  <% if current_user %>
                      <%= link_to "Consulter", lesson_path(lesson.id), class: "btn btn-primary btn-index"  %>
                  <% else %>
                      <%= link_to "Inscris-toi pour consulter", new_user_registration_path, class: "btn btn-primary btn-index" %>
                  <% end %>
                  </div>
                </div>
              </div>
              <div class="separator"></div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <% if current_user %>
    <div class="black-zone">
      <h2 class="title mt-4 white-title">
        N'attends plus :
      </h2>
        <div class="btn-card">
          <div class="btn-group">
              <%= link_to "Ajoute un cours !", new_lesson_path, class: "btn btn-primary big-btn" %>
          </div>
        </div>
    </div>
    <% else %>
    <div class="black-zone">
      <h2 class="title mt-4 white-title">
        N'attends plus :
      </h2>
        <div class="btn-card">
          <div class="btn-group">
              <%= link_to "Inscris-toi !", new_user_registration_path, class: "btn btn-primary big-btn" %>
          </div>
        </div>
    </div>
  <% end %>

<% end %>

app/views/lessons/new.html.erb
<div class="center mt-4" >
<h2 class="text-black title mb-4">
    Ajoute un cours :
  </h2>
<%= form_tag url_for(action:'create'), method: "post", :rows => 10, style: 'width:100%;' do %>
  <% if @lesson.errors.any? %>
  <div class="card-error">
  <h5> Ta ressource n'a pas été ajoutée car : </h5>
  <% @lesson.errors.full_messages.each do |m| %>
  <%= m %>
  <br/>
  <% end %>
  </div>
  <br/>
  <% end %>
  <%= label_tag 'Titre de ta ressource' %><br>
  <small> 5 caractères minimum </small><br/>
  <%= text_field_tag 'title' %>
  <br /> <br />
  <%= label_tag 'Matière' %><br>
  <%= select_tag "top", options_from_collection_for_select(@topics, "id", "name", "1"), class: "form-control" %>
  <br /> <br />
  <%= label_tag 'Contenu de ta ressource' %><br>
  <small> 50 caractères minimum </small><br/>
  <%= text_area_tag 'content', @content, rows: 30, cols: 130 %>
  <br /> <br />
  <%= submit_tag "Partage ta ressource", class: "btn btn-primary" %>
<% end %>
</div>

app/views/lessons/show.html.erb
<div class="center mt-4" >
  <div class="card">
    <div class="row banniere">
      <div class="border_2">
        <div class="card-body body-view">
          <div class="content-view">
            <div class="title-card">
              <h1 class="card-title"><%= @lesson.title %></h1>
            </div>
            <%= form_with(url: favorite_path, method: 'patch') do %>
              <%= button_tag(type: "submit", class: "btn btn-default star-btn") do %>
                <%= image_tag('star.png', class: "star") %>
              <% end %>
            <% end %>
          </div>
          <h5 class="card-subtitle mb-2 text-muted align-start ml-3"> Matière : <%= @lesson.topic.name %></h5>
          <p class="card-text align-start ml-3"><%= simple_format(@lesson.content) %></p>
          <%= link_to " Voir mes favoris", favorite_path(current_user.id) %>
          <%= link_to "Retour à la page d'accueil ", root_path%>
        </div>
        <div class="separator"></div>
        <div class="col-8">

          </br>
          <div class="comment-notes">
            <h4> <%= (@lesson.comments.count) %> <%="commentaire(s) :"%> </h4>
            <div class="card-body card-view">
              <% @lesson.comments.all.each do |comment| %>
              <h4 class="card-title"><%= comment.title %></h4>
              <h6 class="card-subtitle mb-2 text-muted"> <%= "Commentaire de : " %><%= comment.user.first_name %> <%= comment.user.last_name %></h6>
              <p class="card-text"><%= simple_format(comment.content) %></p>
              <% if current_user == comment.user %>
              <%= link_to 'Supprimer mon commentaire', [comment.lesson, comment], method: :delete, data: { confirm: 'Supprimer le commentaire ?' } %>
              <% end %>
              <div class="separator"></div>
              <% end %>
            <h4> Ajouter un commentaire : </h4>
              <%= form_tag comments_path(lesson_id: params['id'], action: 'create') do%>
              <%= label_tag 'Titre de ton commentaire :' %><br>
              <%= text_field_tag :title %><br>
              <%= label_tag 'Contenu de ton commentaire sur la ressource :' %><br>
              <%= text_area_tag :content, @content, rows: 5, cols: 110 %><br>
              <%= submit_tag "Ajouter un commentaire", class: 'btn btn-primary' %>
              <%end%>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/topics/show.html.erb
<h2 class="text-black title mb-4"> <%= @topic_attribute.name %></h2>
<div class="center mt-4" >
    <div class="card">
      <div class="row banniere">
        <% @topic.all.each do |x| %>
          <div class="element">
            <div class="card-body">
              <div class="text-card">
                <h5 class="card-title"><%= x.title %></h5>
                <p class="card-text"><%= strip_tags(x.content[0..100]) %></p>
              </div>
              <div class="btn-card">
                <div class="btn-group">

<a class="btn btn-primary btn-index ml-1" href="<%= lesson_path(x.id) %>" role="button">Voir la ressource</a>
                </div>
              </div>
            </div>
            <div class="separator"></div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= form_for @user do |f| %>
  <section id="cover">
  <div id="cover-caption">
      <div id="container" class="container">
        <div class="row text-black ">
          <div class="col-sm-6 offset-sm-3 text-center">
            <br>
            <h2 class="text-center"> Complète ton profil </h2>
            <br>
            <div class="info-form">
              <div class="form-group">
                <h6 class="text-left">Ton prénom</h6>
                <%= f.text_field :first_name, class: 'form-control' %>
                <br>
                <h6 class="text-left">Ton nom</h6>
                <%= f.text_field :last_name, class: 'form-control' %>
                <br>
                 <h6 class="text-left">Ta ville</h6>
                <%= f.text_field :city, class: 'form-control' %>
                <br>
                <h6 class="text-left">Ton école</h6>
                <%= f.text_field :school, class: 'form-control' %>
                <br>
                <h6 class="text-left">Ton diplôme</h6>
                <%= f.text_field :diploma, class: 'form-control' %>
                <br>
               </div>
               <div class="form-group">
              <div class="actions">
              <%= f.submit "Enregistrer / Editer",class:"btn"%>
            </div>
                <br>
                <%= link_to "Retour à mes informations de profil", :back %>
               </div>
           </div>
         </div>
       </div>
     </div>
    </div>
  </section>
     
  
               <% end %>

app/views/users/index.html.erb
  <h2 class="text-black title mb-4">
    Cours que j'ai partagé(s) sur Learn it:
  </h2>
 <% @all_my_lessons.each do |lesson| %>
            <div class="element">
              <div class="card-body">
                <div class="text-card">
                  <h4 class="card-title"><%= lesson.title %></h4>
                  <h6 class="card-subtitle mb-2 text-muted"><%= lesson.topic.name %></h6>
                  <h6 class="card-subtitle mb-2 text-muted"> <%= "Leçon de moi-même" %></h6>
                  <p class="card-text"><%= strip_tags(lesson.content[0..90]) %></p>
                </div>
                <div class="btn-card">
                  <div class="btn-group">
                  <% if current_user %>
                      <%= link_to "Consulter", lesson_path(lesson.id), class: "btn btn-primary btn-index"  %>
                      <%= link_to 'Supprimer', lesson_path(lesson.id), method: :delete, data: { confirm: 'Supprimer le cours ?' }, class: "btn btn-primary btn-index ml-1" %>
                  <% else %>
                      <%= link_to "Connecte-toi pour consulter", new_user_session_path, class: "btn btn-primary btn-index"  %>
                  <% end %>
                  </div>
                </div>
              </div>
              <div class="separator"></div>
            </div>
          <% end %>

app/views/users/show.html.erb
<br>
<div class="center mt-4" >
<h2 class="center mt-4">Bienvenue sur ton profil</h2>
    <div class="center mt-4">
        <h5 class="card-subtitle mb-2 text-muted">Ton prénom : <%= @user.first_name%></h5>
        <h5 class="card-subtitle mb-2 text-muted">Ton nom : <%= @user.last_name%></h5>
        <h5 class="card-subtitle mb-2 text-muted">Ton email : <%= @user.email%></h5>
        <h5 class="card-subtitle mb-2 text-muted">Ta ville : <%= @user.city%></h5>
        <h5 class="card-subtitle mb-2 text-muted">Ton école : <%= @user.school%></h5>
        <h5 class="card-subtitle mb-2 text-muted">Ton diplôme : <%= @user.diploma%></h5>
        <br/>
        <%= link_to "Modifier mes informations", edit_user_path(@user.id), class: "btn" %>
        <%= link_to "Changer de mot de passe/Quitter Learn it", edit_user_registration_path, class: "btn" %>
      <br>
    </div>
</div>